name: Deploy wheels to pypi
on: push


jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'nodeploy')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Lint Python code
        run: poetry run black --check xudoku/ tests/
      - name: Test package
        run: poetry run test
      - name: Build package
        run: poetry build
